name: Android CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: set up android development environment
      uses: android-actions/setup-android@v2

    - name: install dependencies
      run: |
        sdkmanager --install "cmake;3.22.1"
        echo "cmake.dir=/usr/local/lib/android/sdk/cmake/3.22.1" > local.properties
        npm install -g pnpm

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Update Assets
      run: |
        git submodule foreach --recursive git pull origin main
        git clone https://$ACCESS_TOKEN_GITHUB@github.com/imas-tools/gakumas-raw-txts.git app/src/main/assets/gakumas-local
        mv app/src/main/assets/gakumas-local/gakumas-raw-txts/Resource app/src/main/assets/gakumas-local/raw
        rm -rf app/src/main/assets/gakumas-local/gakumas-raw-txts

    - name: Build Assets
      run: |
        mv app/src/main/assets/gakumas-local/GakumasPreTranslation/.env.sample app/src/main/assets/gakumas-local/GakumasPreTranslation/.env
        cd app/src/main/assets/gakumas-local && make build-resource

    - name: Write branch and commit info
      run: |
        branch=$(git rev-parse --abbrev-ref HEAD)
        hash=$(git rev-parse --short=8 HEAD)
        echo "$branch.$hash" > app/src/main/assets/gakumas-local/version.txt
              
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - uses: actions/upload-artifact@v4
      with:
        name: GakumasLocalify-Unsigned-apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - uses: ilharp/sign-android-release@v1
      name: Sign app APK
      id: sign_app
      with:
        releaseDir: app/build/outputs/apk/debug
        signingKey: ${{ secrets.KEYSTOREB64 }}
        keyAlias: ${{ secrets.ANDROID_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        buildToolsVersion: 33.0.0

    - uses: actions/upload-artifact@v4
      with:
        name: GakumasLocalify-Signed-apk
        path: ${{steps.sign_app.outputs.signedFile}}
